apiVersion: v1
kind: Service
metadata:
    name: asistenciaplusemailnewprivatechat
spec:
    type: LoadBalancer
    ports:
    - port: 12345 
    selector:
        app: asistenciaplusemailnewprivatechat